name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip

    - name: Install requirements
      run: |
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile main.py

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: main-exe
        path: dist/main*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: main-exe

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/main.exe"
        name: Release ${{ github.ref }}
        body: |
          This is the release for version ${{ github.ref }}.
        draft: false
        prerelease: false

    - name: Upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/main.exe
        asset_name: main.exe
        asset_content_type: application/octet-stream
