name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Upgrade Pip
      run: |
        python -m pip install --upgrade pip

    - name: Install requirements
      run: |
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: |
        pip install pyinstaller

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --name fisherman main.py 

    - name: Archive production artifacts
      uses: actions/upload-artifact@v4
      with:
        name: fisherman-windows
        path: dist/*.*

  create_release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: fisherman-windows

    - name: Install GitHub CLI
      run: |
        ls -la
        sudo apt-get update
        sudo apt-get install gh

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME=$(basename ${{ github.ref }})
        gh release create $TAG_NAME fisherman.exe --title "Release $TAG_NAME" --notes "Auto-generated release by GitHub Actions."
